# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11timeservice.proto\"\x15\n\x04Time\x12\r\n\x05value\x18\x01 \x01(\t\"!\n\nTimeUpdate\x12\x13\n\x04time\x18\x01 \x01(\x0b\x32\x05.Time\"\x0c\n\nNowRequest\"#\n\x11TimeStreamRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\x32[\n\x0bTimeService\x12\x1f\n\x03Now\x12\x0b.NowRequest\x1a\x0b.TimeUpdate\x12+\n\x06Stream\x12\x12.TimeStreamRequest\x1a\x0b.TimeUpdate0\x01\x42\x04Z\x02pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002pb'
  _TIME._serialized_start=21
  _TIME._serialized_end=42
  _TIMEUPDATE._serialized_start=44
  _TIMEUPDATE._serialized_end=77
  _NOWREQUEST._serialized_start=79
  _NOWREQUEST._serialized_end=91
  _TIMESTREAMREQUEST._serialized_start=93
  _TIMESTREAMREQUEST._serialized_end=128
  _TIMESERVICE._serialized_start=130
  _TIMESERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
